[package]
name = "hive-ld53"
description = "An unsuccesful LD 53 attempt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad="0.3"
